# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bytch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bytch
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  

  platform :ios, '9.0'
  target 'BytchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Bytch-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bytch-tvOS

  target 'Bytch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
